/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Inquiry {
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type InquiryId = bigint;
export interface Pdf {
  'title' : string,
  'file' : ExternalBlob,
  'description' : string,
}
export type PdfId = bigint;
export interface Product {
  'name' : string,
  'size' : string,
  'description' : string,
  'category' : string,
  'material' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'title' : string,
  'file' : ExternalBlob,
  'description' : string,
}
export type VideoId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePdf' : ActorMethod<[PdfId], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteVideo' : ActorMethod<[VideoId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getPdfs' : ActorMethod<[], Array<Pdf>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getVideos' : ActorMethod<[], Array<Video>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'seedProducts' : ActorMethod<[], undefined>,
  'submitInquiry' : ActorMethod<[string, string, string, string], InquiryId>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
  'uploadPdf' : ActorMethod<[string, string, ExternalBlob], PdfId>,
  'uploadVideo' : ActorMethod<[string, string, ExternalBlob], VideoId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];